app:
  image: loginchapchap
  ports:
    - "86:3000"
  links:
    - mongo
  environment:
    - ROOT_URL=http://localhost
    - MONGO_URL=mongodb://mongo:27017/meteor
    - 'METEOR_SETTINGS={"DBSQLSERVER_HOST":"10.10.3.65","DBSQLSERVER_PORT":"","DBSQLSERVER_USER":"nsiavie","DBSQLSERVER_PASSWORD":"nsiavie","DBSQLSERVER_DATABASE":"DB_EXTRANET_VIE"}'
  restart: always
mongo:
  image: mongo:latest 
  restart: always
